export type Indicator = {
  code: string;
  name: string;
  unit: string;
  source: string;
  sourceUrl?: string;
  topic: string;
  sdgGoal?: number;
  sdgTarget?: string;
  sdgTargetValue?: number;
  sdgDirection: "lower-is-better" | "higher-is-better";
  relatedIndicators: string[];
  driverIndicators: string[];
  precision: number;
  coverageNote?: string;
  uncertaintyIndicators?: { upper: string; lower: string };
};

export const INDICATORS: Indicator[] = [
  // Health (SDG 3)
  {
    code: "SH.STA.MMRT",
    name: "Maternal mortality ratio",
    unit: "per 100,000 live births",
    source: "WHO / UN MMEIG",
    topic: "Health",
    sdgGoal: 3,
    sdgTarget: "3.1",
    sdgTargetValue: 70,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "SH.DYN.MORT",
      "SP.DYN.LE00.IN",
      "SH.STA.BRTC.ZS",
      "SH.XPD.CHEX.GD.ZS",
    ],
    driverIndicators: [
      "SH.STA.BRTC.ZS",
      "SH.STA.ANV4.ZS",
      "SP.DYN.CONU.ZS",
      "SP.ADO.TFRT",
      "SH.XPD.CHEX.GD.ZS",
    ],
    precision: 0,
    coverageNote: "Modelled estimates, 2000 onward",
    uncertaintyIndicators: { upper: "SH.STA.MMRT.UB", lower: "SH.STA.MMRT.LB" },
  },
  {
    code: "SH.DYN.MORT",
    name: "Under-5 mortality rate",
    unit: "per 1,000 live births",
    source: "UN Inter-agency Group for Child Mortality Estimation",
    topic: "Health",
    sdgGoal: 3,
    sdgTarget: "3.2",
    sdgTargetValue: 25,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "SH.STA.MMRT",
      "SP.DYN.LE00.IN",
      "SH.IMM.MEAS",
      "SH.STA.STNT.ZS",
    ],
    driverIndicators: [
      "SH.STA.BRTC.ZS",
      "SH.IMM.MEAS",
      "SH.STA.STNT.ZS",
      "SH.H2O.BASW.ZS",
    ],
    precision: 1,
  },
  {
    code: "SP.DYN.LE00.IN",
    name: "Life expectancy at birth",
    unit: "years",
    source: "UN Population Division",
    topic: "Health",
    sdgGoal: 3,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SH.DYN.MORT",
      "SH.STA.MMRT",
      "SH.XPD.CHEX.GD.ZS",
    ],
    driverIndicators: [
      "SH.DYN.MORT",
      "SH.XPD.CHEX.GD.ZS",
      "SH.STA.STNT.ZS",
    ],
    precision: 1,
  },
  {
    code: "SH.IMM.MEAS",
    name: "Measles immunization, children ages 12-23 months",
    unit: "% of children",
    source: "WHO and UNICEF",
    topic: "Health",
    sdgGoal: 3,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SH.DYN.MORT",
      "SH.XPD.CHEX.GD.ZS",
      "SH.MED.PHYS.ZS",
    ],
    driverIndicators: [
      "SH.XPD.CHEX.GD.ZS",
      "SH.MED.PHYS.ZS",
    ],
    precision: 1,
  },
  {
    code: "SH.XPD.CHEX.GD.ZS",
    name: "Current health expenditure (% of GDP)",
    unit: "% of GDP",
    source: "WHO Global Health Expenditure Database",
    topic: "Health",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SH.STA.MMRT",
      "SH.DYN.MORT",
      "SP.DYN.LE00.IN",
      "SH.IMM.MEAS",
    ],
    driverIndicators: [],
    precision: 1,
  },

  // Education (SDG 4)
  {
    code: "SE.ADT.LITR.ZS",
    name: "Literacy rate, adult total",
    unit: "% of people ages 15 and above",
    source: "UNESCO Institute for Statistics",
    topic: "Education",
    sdgGoal: 4,
    sdgTarget: "4.6",
    sdgTargetValue: 100,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SE.PRM.ENRR",
      "SE.SEC.ENRR",
      "SE.XPD.TOTL.GD.ZS",
    ],
    driverIndicators: [
      "SE.PRM.ENRR",
      "SE.SEC.ENRR",
      "SE.XPD.TOTL.GD.ZS",
    ],
    precision: 1,
  },
  {
    code: "SE.PRM.ENRR",
    name: "School enrollment, primary (gross)",
    unit: "% gross",
    source: "UNESCO Institute for Statistics",
    topic: "Education",
    sdgGoal: 4,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SE.ADT.LITR.ZS",
      "SE.SEC.ENRR",
      "SE.XPD.TOTL.GD.ZS",
      "SE.ENR.PRSC.FM.ZS",
    ],
    driverIndicators: [
      "SE.XPD.TOTL.GD.ZS",
      "SE.ENR.PRSC.FM.ZS",
    ],
    precision: 1,
  },
  {
    code: "SE.SEC.ENRR",
    name: "School enrollment, secondary (gross)",
    unit: "% gross",
    source: "UNESCO Institute for Statistics",
    topic: "Education",
    sdgGoal: 4,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SE.PRM.ENRR",
      "SE.TER.ENRR",
      "SE.XPD.TOTL.GD.ZS",
      "SE.ENR.PRSC.FM.ZS",
    ],
    driverIndicators: [
      "SE.XPD.TOTL.GD.ZS",
      "SE.ENR.PRSC.FM.ZS",
    ],
    precision: 1,
  },
  {
    code: "SE.TER.ENRR",
    name: "School enrollment, tertiary (gross)",
    unit: "% gross",
    source: "UNESCO Institute for Statistics",
    topic: "Education",
    sdgGoal: 4,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SE.SEC.ENRR",
      "SE.XPD.TOTL.GD.ZS",
      "NY.GDP.PCAP.CD",
    ],
    driverIndicators: [
      "SE.XPD.TOTL.GD.ZS",
      "NY.GDP.PCAP.CD",
    ],
    precision: 1,
  },
  {
    code: "SE.XPD.TOTL.GD.ZS",
    name: "Government expenditure on education, total (% of GDP)",
    unit: "% of GDP",
    source: "UNESCO Institute for Statistics",
    topic: "Education",
    sdgGoal: 4,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SE.PRM.ENRR",
      "SE.SEC.ENRR",
      "SE.ADT.LITR.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },
  {
    code: "SE.ENR.PRSC.FM.ZS",
    name: "School enrollment, primary and secondary (gross), gender parity index (GPI)",
    unit: "GPI",
    source: "UNESCO Institute for Statistics",
    topic: "Education",
    sdgGoal: 4,
    sdgTarget: "4.5",
    sdgTargetValue: 1,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SE.PRM.ENRR",
      "SE.SEC.ENRR",
      "SL.TLF.CACT.FE.ZS",
    ],
    driverIndicators: [
      "SE.PRM.ENRR",
      "SE.SEC.ENRR",
    ],
    precision: 2,
  },

  // Economy
  {
    code: "NY.GDP.MKTP.CD",
    name: "GDP (current US$)",
    unit: "current US$",
    source: "World Bank national accounts data",
    topic: "Economy",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "NY.GDP.PCAP.CD",
      "NY.GDP.PCAP.KD.ZG",
      "GC.DOD.TOTL.GD.ZS",
    ],
    driverIndicators: [
      "NY.GDP.PCAP.KD.ZG",
      "SP.POP.TOTL",
    ],
    precision: 0,
  },
  {
    code: "NY.GDP.PCAP.CD",
    name: "GDP per capita (current US$)",
    unit: "current US$",
    source: "World Bank national accounts data",
    topic: "Economy",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "NY.GDP.MKTP.CD",
      "NY.GDP.PCAP.KD.ZG",
      "SI.POV.DDAY",
      "SL.UEM.TOTL.ZS",
    ],
    driverIndicators: [
      "NY.GDP.PCAP.KD.ZG",
      "SL.UEM.TOTL.ZS",
      "SL.TLF.CACT.FE.ZS",
    ],
    precision: 0,
  },
  {
    code: "NY.GDP.PCAP.KD.ZG",
    name: "GDP per capita growth (annual %)",
    unit: "annual %",
    source: "World Bank national accounts data",
    topic: "Economy",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "NY.GDP.PCAP.CD",
      "FP.CPI.TOTL.ZG",
      "SL.UEM.TOTL.ZS",
    ],
    driverIndicators: [
      "FP.CPI.TOTL.ZG",
      "GC.DOD.TOTL.GD.ZS",
    ],
    precision: 1,
  },
  {
    code: "FP.CPI.TOTL.ZG",
    name: "Inflation, consumer prices (annual %)",
    unit: "annual %",
    source: "International Monetary Fund, International Financial Statistics",
    topic: "Economy",
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "NY.GDP.PCAP.KD.ZG",
      "GC.DOD.TOTL.GD.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },
  {
    code: "SL.UEM.TOTL.ZS",
    name: "Unemployment, total (% of total labor force)",
    unit: "% of total labor force",
    source: "International Labour Organization",
    topic: "Economy",
    sdgGoal: 8,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "NY.GDP.PCAP.CD",
      "SL.TLF.CACT.FE.ZS",
      "SI.POV.DDAY",
    ],
    driverIndicators: [
      "NY.GDP.PCAP.KD.ZG",
      "SE.SEC.ENRR",
    ],
    precision: 1,
  },
  {
    code: "SL.TLF.CACT.FE.ZS",
    name: "Labor force participation rate, female (% of female population ages 15+)",
    unit: "% of female population ages 15+",
    source: "International Labour Organization",
    topic: "Economy",
    sdgGoal: 8,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SL.UEM.TOTL.ZS",
      "SE.ENR.PRSC.FM.ZS",
      "NY.GDP.PCAP.CD",
    ],
    driverIndicators: [
      "SE.SEC.ENRR",
      "SE.ENR.PRSC.FM.ZS",
    ],
    precision: 1,
  },
  {
    code: "GC.DOD.TOTL.GD.ZS",
    name: "Central government debt, total (% of GDP)",
    unit: "% of GDP",
    source: "IMF Government Finance Statistics Yearbook",
    topic: "Economy",
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "NY.GDP.PCAP.KD.ZG",
      "FP.CPI.TOTL.ZG",
    ],
    driverIndicators: [],
    precision: 1,
  },

  // Poverty & inequality (SDG 1, 10)
  {
    code: "SI.POV.DDAY",
    name: "Poverty headcount ratio at $2.15 a day (2017 PPP)",
    unit: "% of population",
    source: "World Bank Poverty and Inequality Platform",
    topic: "Poverty & inequality",
    sdgGoal: 1,
    sdgTarget: "1.1",
    sdgTargetValue: 0,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "SI.POV.NAHC",
      "SI.POV.GINI",
      "NY.GDP.PCAP.CD",
    ],
    driverIndicators: [
      "NY.GDP.PCAP.KD.ZG",
      "SI.POV.GINI",
      "SL.UEM.TOTL.ZS",
    ],
    precision: 1,
  },
  {
    code: "SI.POV.NAHC",
    name: "Poverty headcount ratio at national poverty lines (% of population)",
    unit: "% of population",
    source: "World Bank Poverty and Inequality Platform",
    topic: "Poverty & inequality",
    sdgGoal: 1,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "SI.POV.DDAY",
      "SI.POV.GINI",
    ],
    driverIndicators: [
      "NY.GDP.PCAP.KD.ZG",
      "SL.UEM.TOTL.ZS",
    ],
    precision: 1,
  },
  {
    code: "SI.POV.GINI",
    name: "Gini index",
    unit: "index (0–100)",
    source: "World Bank Poverty and Inequality Platform",
    topic: "Poverty & inequality",
    sdgGoal: 10,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "SI.POV.DDAY",
      "NY.GDP.PCAP.CD",
      "SL.TLF.CACT.FE.ZS",
    ],
    driverIndicators: [
      "SE.ADT.LITR.ZS",
      "SL.TLF.CACT.FE.ZS",
    ],
    precision: 1,
  },

  // Environment & energy (SDG 7, 13)
  {
    code: "EG.ELC.ACCS.ZS",
    name: "Access to electricity (% of population)",
    unit: "% of population",
    source: "World Bank, Sustainable Energy for All database",
    topic: "Environment & energy",
    sdgGoal: 7,
    sdgTarget: "7.1",
    sdgTargetValue: 100,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "EG.FEC.RNEW.ZS",
      "EG.ELC.LOSS.ZS",
      "IT.NET.USER.ZS",
    ],
    driverIndicators: [
      "NY.GDP.PCAP.CD",
      "EG.ELC.LOSS.ZS",
    ],
    precision: 1,
  },
  {
    code: "EG.FEC.RNEW.ZS",
    name: "Renewable energy consumption (% of total final energy consumption)",
    unit: "% of total final energy consumption",
    source: "IEA Statistics",
    topic: "Environment & energy",
    sdgGoal: 7,
    sdgTarget: "7.2",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "EG.ELC.ACCS.ZS",
      "EN.ATM.CO2E.PC",
    ],
    driverIndicators: [],
    precision: 1,
  },
  {
    code: "EN.ATM.CO2E.PC",
    name: "CO2 emissions (metric tons per capita)",
    unit: "metric tons per capita",
    source: "Carbon Dioxide Information Analysis Center",
    topic: "Environment & energy",
    sdgGoal: 13,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "EG.FEC.RNEW.ZS",
      "EG.ELC.ACCS.ZS",
      "NY.GDP.PCAP.CD",
    ],
    driverIndicators: [
      "EG.FEC.RNEW.ZS",
      "NY.GDP.PCAP.CD",
    ],
    precision: 2,
  },
  {
    code: "AG.LND.FRST.ZS",
    name: "Forest area (% of land area)",
    unit: "% of land area",
    source: "Food and Agriculture Organization",
    topic: "Environment & energy",
    sdgGoal: 15,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "EN.ATM.CO2E.PC",
      "ER.H2O.FWTL.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },
  {
    code: "ER.H2O.FWTL.ZS",
    name: "Annual freshwater withdrawals, total (% of internal resources)",
    unit: "% of internal resources",
    source: "Food and Agriculture Organization AQUASTAT",
    topic: "Environment & energy",
    sdgGoal: 6,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "AG.LND.FRST.ZS",
      "SH.H2O.BASW.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },

  // Infrastructure & digital (SDG 9)
  {
    code: "IT.NET.USER.ZS",
    name: "Individuals using the Internet (% of population)",
    unit: "% of population",
    source: "International Telecommunication Union",
    topic: "Infrastructure & digital",
    sdgGoal: 9,
    sdgTarget: "9.c",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "IT.CEL.SETS.P2",
      "EG.ELC.ACCS.ZS",
      "SE.TER.ENRR",
    ],
    driverIndicators: [
      "EG.ELC.ACCS.ZS",
      "NY.GDP.PCAP.CD",
    ],
    precision: 1,
  },
  {
    code: "IT.CEL.SETS.P2",
    name: "Mobile cellular subscriptions (per 100 people)",
    unit: "per 100 people",
    source: "International Telecommunication Union",
    topic: "Infrastructure & digital",
    sdgGoal: 9,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "IT.NET.USER.ZS",
      "EG.ELC.ACCS.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },
  {
    code: "IS.ROD.PAVE.ZS",
    name: "Roads, paved (% of total roads)",
    unit: "% of total roads",
    source: "International Road Federation",
    topic: "Infrastructure & digital",
    sdgGoal: 9,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "NY.GDP.PCAP.CD",
      "EG.ELC.ACCS.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },
  {
    code: "EG.ELC.LOSS.ZS",
    name: "Electric power transmission and distribution losses (% of output)",
    unit: "% of output",
    source: "IEA Statistics",
    topic: "Infrastructure & digital",
    sdgGoal: 7,
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "EG.ELC.ACCS.ZS",
      "EG.FEC.RNEW.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },

  // Demographics
  {
    code: "SP.POP.TOTL",
    name: "Population, total",
    unit: "persons",
    source: "UN Population Division",
    topic: "Demographics",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SP.POP.GROW",
      "SP.URB.TOTL.IN.ZS",
      "SP.DYN.TFRT.IN",
    ],
    driverIndicators: [
      "SP.DYN.TFRT.IN",
      "SP.DYN.LE00.IN",
    ],
    precision: 0,
  },
  {
    code: "SP.POP.GROW",
    name: "Population growth (annual %)",
    unit: "annual %",
    source: "UN Population Division",
    topic: "Demographics",
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SP.POP.TOTL",
      "SP.DYN.TFRT.IN",
      "SP.URB.TOTL.IN.ZS",
    ],
    driverIndicators: [
      "SP.DYN.TFRT.IN",
      "SP.DYN.LE00.IN",
    ],
    precision: 2,
  },
  {
    code: "SP.URB.TOTL.IN.ZS",
    name: "Urban population (% of total population)",
    unit: "% of total population",
    source: "UN Population Division",
    topic: "Demographics",
    sdgGoal: 11,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "SP.POP.TOTL",
      "IT.NET.USER.ZS",
      "EG.ELC.ACCS.ZS",
    ],
    driverIndicators: [],
    precision: 1,
  },
  {
    code: "SP.DYN.TFRT.IN",
    name: "Fertility rate, total (births per woman)",
    unit: "births per woman",
    source: "UN Population Division",
    topic: "Demographics",
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "SP.POP.GROW",
      "SH.STA.MMRT",
      "SE.ADT.LITR.ZS",
    ],
    driverIndicators: [
      "SE.ADT.LITR.ZS",
      "SH.STA.MMRT",
      "SP.DYN.CONU.ZS",
    ],
    precision: 2,
  },
  {
    code: "SP.POP.DPND",
    name: "Age dependency ratio (% of working-age population)",
    unit: "% of working-age population",
    source: "UN Population Division",
    topic: "Demographics",
    sdgDirection: "lower-is-better",
    relatedIndicators: [
      "SP.DYN.TFRT.IN",
      "SP.POP.GROW",
      "SL.UEM.TOTL.ZS",
    ],
    driverIndicators: [
      "SP.DYN.TFRT.IN",
    ],
    precision: 1,
  },

  // Governance (SDG 16)
  {
    code: "IQ.CPA.PROP.XQ",
    name: "CPIA property rights and rule-based governance rating",
    unit: "rating (1–6)",
    source: "World Bank Country Policy and Institutional Assessment",
    topic: "Governance",
    sdgGoal: 16,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "IQ.CPA.TRAN.XQ",
      "NY.GDP.PCAP.KD.ZG",
    ],
    driverIndicators: [],
    precision: 1,
    coverageNote: "IDA-eligible countries only",
  },
  {
    code: "IQ.CPA.TRAN.XQ",
    name: "CPIA transparency, accountability, and corruption in the public sector rating",
    unit: "rating (1–6)",
    source: "World Bank Country Policy and Institutional Assessment",
    topic: "Governance",
    sdgGoal: 16,
    sdgDirection: "higher-is-better",
    relatedIndicators: [
      "IQ.CPA.PROP.XQ",
      "GC.DOD.TOTL.GD.ZS",
    ],
    driverIndicators: [],
    precision: 1,
    coverageNote: "IDA-eligible countries only",
  },
];

export const INDICATOR_MAP = new Map<string, Indicator>(
  INDICATORS.map((ind) => [ind.code, ind])
);

export function getIndicator(code: string): Indicator | undefined {
  return INDICATOR_MAP.get(code);
}
